//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.Fatura_Kalem = new HashSet<Fatura_Kalem>();
        }
    
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public int MusteriID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FaturaKodu { get; set; }
        public string Sıra { get; set; }
        public string Seri { get; set; }
        public string OzelestirmeNo { get; set; }
        public string Senaryo { get; set; }
        public string FaturaNo { get; set; }
    
        public virtual FirmaBilgileri FirmaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura_Kalem> Fatura_Kalem { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
