//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaBilgileri()
        {
            this.Fatura = new HashSet<Fatura>();
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdresi { get; set; }
        public string TelefonNo { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarası { get; set; }
        public string EmailAdresi { get; set; }
        public string FaxNo { get; set; }
        public Nullable<int> OncekiID { get; set; }
        public Nullable<int> SonrakiID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
