//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiyatKayit
    {
        public int ID { get; set; }
        public int MalzemeID { get; set; }
        public decimal Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Alis { get; set; }
        public Nullable<bool> Satis { get; set; }
    
        public virtual Malzeme Malzeme { get; set; }
    }
}
