//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Irsaliye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Irsaliye()
        {
            this.Irsaliye_Kalem = new HashSet<Irsaliye_Kalem>();
        }
    
        public int İrsaliyeID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public string SiraNo { get; set; }
        public string SeriNo { get; set; }
        public string TeslimEden { get; set; }
        public string AracPlakaNo { get; set; }
        public Nullable<int> TeslimAlanID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Irsaliye_Kalem> Irsaliye_Kalem { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
