//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kalem()
        {
            this.Fatura_Kalem = new HashSet<Fatura_Kalem>();
            this.Irsaliye_Kalem = new HashSet<Irsaliye_Kalem>();
            this.Siparis_Kalem = new HashSet<Siparis_Kalem>();
        }
    
        public int KalemID { get; set; }
        public int KalemNo { get; set; }
        public int MalzemeID { get; set; }
        public int MalzemeMiktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string ParaBirimi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura_Kalem> Fatura_Kalem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Irsaliye_Kalem> Irsaliye_Kalem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Kalem> Siparis_Kalem { get; set; }
    }
}
