//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kisi()
        {
            this.Musteri_Kisi = new HashSet<Musteri_Kisi>();
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int ID { get; set; }
        public string AdOnEki { get; set; }
        public string Ad { get; set; }
        public string AdIkinci { get; set; }
        public string Soyad { get; set; }
        public string Unvan { get; set; }
        public string TelefonIs { get; set; }
        public string TelefonCep { get; set; }
        public string EmailAdresi { get; set; }
        public string AracPlakasi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri_Kisi> Musteri_Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
