//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public int HedefTur { get; set; }
        public int LogTuru { get; set; }
        public int PersonelID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string EskiVersiyon { get; set; }
        public string YeniVersiyon { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
