//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malzeme()
        {
            this.FiyatKayit = new HashSet<FiyatKayit>();
        }
    
        public int ID { get; set; }
        public string FirmaMalzemeKodu { get; set; }
        public string Tanim { get; set; }
        public string RevNo { get; set; }
        public string TeknikBilgiPaketi { get; set; }
        public string MalzemeTuru { get; set; }
        public string TeknikCizimYolu { get; set; }
        public string Veri3Dyolu { get; set; }
        public Nullable<int> Tedarikci { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public Nullable<int> StokMiktarı { get; set; }
        public Nullable<int> MinSiparis { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiyatKayit> FiyatKayit { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
