//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis_Kalem
    {
        public int ID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> KalemID { get; set; }
    
        public virtual Kalem Kalem { get; set; }
        public virtual Siparis Siparis { get; set; }
    }
}
