//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.Siparis_Kalem = new HashSet<Siparis_Kalem>();
        }
    
        public int ID { get; set; }
        public string SipNo { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public Nullable<int> İlgiliKisiID { get; set; }
    
        public virtual FirmaBilgileri FirmaBilgileri { get; set; }
        public virtual Kisi Kisi { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Kalem> Siparis_Kalem { get; set; }
    }
}
