//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENFAPRJDBEntities : DbContext
    {
        public ENFAPRJDBEntities()
            : base("name=ENFAPRJDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Fatura_Kalem> Fatura_Kalem { get; set; }
        public virtual DbSet<FirmaBilgileri> FirmaBilgileri { get; set; }
        public virtual DbSet<FiyatKayit> FiyatKayit { get; set; }
        public virtual DbSet<Irsaliye> Irsaliye { get; set; }
        public virtual DbSet<Irsaliye_Kalem> Irsaliye_Kalem { get; set; }
        public virtual DbSet<Kalem> Kalem { get; set; }
        public virtual DbSet<Kisi> Kisi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Malzeme> Malzeme { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Musteri_Kisi> Musteri_Kisi { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<Siparis_Kalem> Siparis_Kalem { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
